- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_PKI_DIR }}/{{ INT_CERT_NAME }}"
  register: int_crt
  delegate_to: vault

- name: Copy CA crt
  copy:
    content: "{{ int_crt['content'] | b64decode }}"
    dest: "/opt/kubernetes/tls/ca.crt"

- name: Slurp vault_int_ca.key
  slurp:
    src: "{{ VAULT_PKI_DIR }}/vault_int_ca.key"
  register: vault_int_ca_key
  delegate_to: vault

- name: Copy CA key
  copy:
    content: "{{ vault_int_ca_key['content'] | b64decode }}"
    dest: "/opt/kubernetes/tls/ca.key"
  notify: Restart kubernetes server service
