- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_CERT_DIR }}/vault_int_ca.crt"
  register: vault_int_ca_crt
  delegate_to: vault

- name: Copy etcd CA certificate
  copy:
    content: "{{ vault_int_ca_crt['content'] | b64decode }}"
    dest: /opt/etcd/tls/ca.crt
    mode: 0644
  notify: Restart kubernetes server service
