- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_CERT_DIR }}/{{ VAULT_INT_CERT_NAME }}"
  register: vault_int_ca_crt
  delegate_to: vault

- name: Copy etcd CA certificate
  copy:
    content: "{{ vault_int_ca_crt['content'] | b64decode }}"
    dest: "{{ ETCD_PKI_DIR }}/ca.crt"
    mode: 0644
  notify: Restart kubernetes server service
