- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_PKI_DIR }}/{{ INT_CERT_NAME }}"
  register: int_crt
  delegate_to: vault

- name: Copy etcd CA certificate
  copy:
    content: "{{ int_crt['content'] | b64decode }}"
    dest: "{{ ETCD_PKI_DIR }}/ca.crt"
    mode: 0644
  notify: Restart kubernetes server service
