- name: Extract kubernetes package
  unarchive:
    src: "{{ KUBERNETES_SERVER_PACKAGE }}"
    dest: /tmp/kubernetes
    creates: /tmp/kubernetes/server
    extra_opts: [ "--strip-components=1" ]

- name: Install kubernetes components
  copy:
    remote_src: yes
    src: "/tmp/kubernetes/server/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl
  notify: Restart kubernetes server service

- name: Add kubernetes basic systemd service
  copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  notify: Restart kubernetes server service

- name: Add kubernetes custom server service
  template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/kube-{{ item.dest }}.service.d/10-{{ item.dest }}.conf"
    mode: 0644
  with_items:
    - { src: apiserver.service.j2, dest: apiserver }
    - { src: controller-manager.service.j2, dest: controller-manager }
    - { src: scheduler.service.j2, dest: scheduler }
  notify: Restart kubernetes server service

- include_tasks: template-controller-manager-conf.yaml
- include_tasks: template-admain-conf.yaml
- include_tasks: template-scheduler-conf.yaml
- include_tasks: copy-int-ca.yaml
- include_tasks: copy-etcd-ca.yaml

- name: Copy kubectl config
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0644

- name: Add kubectl complete for bash
  lineinfile:
    dest: /root/.bashrc
    line: source /usr/share/bash-completion/bash_completion && source <(kubectl completion bash)
    state: present
