- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_CERT_DIR }}/{{ VAULT_INT_CERT_NAME }}"
  register: vault_int_ca_crt
  delegate_to: vault

- name: Slurp controller-manager-apiserver-client.crt
  slurp:
    src: "/opt/kubernetes/tls/controller-manager-apiserver-client.crt"
  register: controller_manager_apiserver_client_crt

- name: Slurp controller-manager-apiserver-client.key
  slurp:
    src: "/opt/kubernetes/tls/controller-manager-apiserver-client.key"
  register: controller_manager_apiserver_client_key

- name: Add controller-manager.conf
  template:
    src: controller-manager.conf.j2
    dest: /etc/kubernetes/controller-manager.conf
    mode: 0644
  notify: Restart kubernetes server service
