- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_CERT_DIR }}/{{ VAULT_INT_CERT_NAME }}"
  register: vault_int_ca_crt
  delegate_to: vault

- name: Slurp scheduler-apiserver-client.crt
  slurp:
    src: "/opt/kubernetes/tls/scheduler-apiserver-client.crt"
  register: scheduler_apiserver_client_crt

- name: Slurp scheduler-apiserver-client.key
  slurp:
    src: "/opt/kubernetes/tls/scheduler-apiserver-client.key"
  register: scheduler_apiserver_client_key

- name: Add scheduler.conf
  template:
    src: scheduler.conf.j2
    dest: /etc/kubernetes/scheduler.conf
    mode: 0644
  notify: Restart kubernetes server service
