- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_CERT_DIR }}/{{ VAULT_INT_CERT_NAME }}"
  register: vault_int_ca_crt
  delegate_to: vault

- name: Slurp admin.crt
  slurp:
    src: "/opt/kubernetes/tls/admin.crt"
  register: admin_crt

- name: Slurp admin.key
  slurp:
    src: "/opt/kubernetes/tls/admin.key"
  register: admin_key

- name: Add admin.conf
  template:
    src: admin.conf.j2
    dest: /etc/kubernetes/admin.conf
    mode: 0644
  notify: Restart kubernetes server service