---
# common land
PKI_TTL: 8760h
MAX_PKI_TTL: 17520h
RESOURCES_PATH: ../resources

# KUBERNETES
kubernetes_version: v1.21.0
server_port: 6443
KUBERNETES_EXTRACT_DIR: /opt/kubernetes
kubernetes_config_directory: /etc/kubernetes
kubernetes_manifests_directory: "{{ kubernetes_config_directory }}/manifests"
kubernetes_pki_directory: "{{ kubernetes_config_directory }}/pki"
kubernetes_ca_certificate: ca.crt
kubernetes_ca_key: ca.key

# ETCD
ETCD_CONFIG_DIR: /etc/etcd
ETCD_PKI_DIR: "{{ ETCD_CONFIG_DIR }}/pki"
ETCD_CA_CERT_NAME: ca.crt
ETCD_CA_KEY_NAME: ca.key

# HARBOR
HARBOR_FQDN: harbor.lan

# DNS
FALLBACK_DNS: 114.114.114.114

# VAULT
VAULT_FQDN: vault.lan
VAULT_PORT: 8200
VAULT_PKI_DIR: /etc/vault/pki
VAULT_CERT_NAME: tls.crt
VAULT_KEY_NAME: tls.key
VAULT_CSR_NAME: tls.csr
VAULT_INITIALIZE_RESULT: initialize_result.json

# GITLAB
GITLAB_FQDN: gitlab.lan
EXTERNAL_URL: https://gitlab.lan
