---
# common land
BASE_FQDN: ipool.me
NAME: radix10
PKI_TTL: 8760h
MAX_PKI_TTL: 17520h
RESOURCES_PATH: ../resources

# ETCD
ETCD_DOWNLOAD_URL: https://storage.googleapis.com/etcd/v3.4.15/etcd-v3.4.15-linux-amd64.tar.gz
ETCD_PACKAGE:  "{{ RESOURCES_PATH }}/etcd/etcd-linux-amd64.tar.gz"

# KUBERNETES
KUBERNETES_CONFIG_DIRECTORY: /etc/kubernetes
PAUSE_VERSION: 3.3
# kubernetes server
KUBERNETES_SERVER_DOWNLOAD_URL: https://dl.k8s.io/v1.20.4/kubernetes-server-linux-amd64.tar.gz
KUBERNETES_SERVER_PACKAGE: "{{ RESOURCES_PATH }}/kubernetes/kubernetes-server-linux-amd64.tar.gz"
# kubernetes node
KUBERNETES_NODE_DOWNLOAD_URL: https://dl.k8s.io/v1.20.4/kubernetes-node-linux-amd64.tar.gz
KUBERNETES_NODE_PACKAGE: "{{ RESOURCES_PATH }}/kubernetes/kubernetes-node-linux-amd64.tar.gz"
# cni plugins
CNI_PLUGINS_DOWNLOAD_URL: https://ghproxy.com/https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
CNI_PLUGINS_PACKAGE: "{{ RESOURCES_PATH }}/kubernetes/cni-plugins-linux-amd64.tar.gz"
# flannel manifests
FLANNEL_MANIFESTS_DOWNLOAD_URL: https://ghproxy.com/https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
FLANNEL_MANIFESTS_FILE: "{{ RESOURCES_PATH }}/kubernetes/kube-flannel.yml"
# kubelet
CLUSTER_DNS: 10.96.0.10

# HARBOR
HARBOR_FQDN: harbor.ipool.me
HARBOR_DOWNLOAD_URL: https://ghproxy.com/https://github.com/goharbor/harbor/releases/download/v2.2.0/harbor-offline-installer-v2.2.0.tgz
HARBOR_PACKAGE:  "{{ RESOURCES_PATH }}/harbor/harbor-offline-installer.tgz"

# BIND
FALLBACK_DNS: 114.114.114.114

# VAULT
VAULT_FQDN: vault.ipool.me
VAULT_PORT: 8200
VAULT_OFFLINE_INSTALL: True
VAULT_DOWNLOAD_URL: https://apt.releases.hashicorp.com/pool/amd64/main/vault_1.7.0_amd64.deb
VAULT_PACKAGE: "{{ RESOURCES_PATH }}/vault/vault.deb"
VAULT_KEY_DIR: /opt/vault/tls

# GITLAB
GITLAB_FQDN: gitlab.ipool.me
EXTERNAL_URL: https://gitlab.ipool.me

# APT
APT_CACHE_HOST: 192.168.123.101
ENABLE_APT_CACHE: no
