---
# Initialize vault
- name: Config vault service
  template:
    src: "vault.hcl.j2"
    dest: "/etc/vault.d/vault.hcl"
    mode: 0644
    group: vault
    owner: vault

- name: Enable and start vault service
  systemd:
    name: vault
    enabled: yes
    state: started

- name: Wait vault to be available
  wait_for:
    host: "{{ VAULT_DOMAIN }}"
    port: "{{ VAULT_PORT }}"

- name: Initialize the vault
  uri:
    method: PUT
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/sys/init"
    body_format: json
    body:
      secret_shares: 3
      secret_threshold: 2
  register: initialize_result

- name: Persistent initialize result
  copy:
    content: "{{ initialize_result.json }}"
    dest: "{{ VAULT_PKI_DIR }}/{{ VAULT_INITIALIZE_RESULT }}"

# Set VAULT_ADDR
- name: Set VAULT_ADDR
  lineinfile:
    dest: /root/.bashrc
    line: export VAULT_ADDR=https://vault:8200
    state: present
