---
- name: Check vault initialize stat
  stat:
    path: "{{ VAULT_PKI_DIR }}/{{ VAULT_INITIALIZE_RESULT }}"
  register: vault_init

- name: Try initialize vault
  include_tasks: initialize-vault.yaml
  when: not vault_init.stat.exists

- name: Unseal vault
  include_tasks: unseal-vault.yaml

- name: Try mount pki root cecret engine
  include_tasks: mount-root-pki-secret-engine.yaml

- name: Try generate root CA certificate
  include_tasks: generate-root-ca.yaml

- name: Try mount pki int cecret engine
  include_tasks: mount-int-pki-secret-engine.yaml

- name: Try generate int CA certificate
  include_tasks: generate-int-ca.yaml
