---
- name: Extract kubernetes package
  unarchive:
    src: "{{ NODE_PACKAGE_NAME }}"
    dest: "{{ EXTRACT_DIR }}"
    creates: "{{ EXTRACT_DIR }}/node"
    extra_opts: [ "--strip-components=1" ]

- name: Install kubelet and proxy
  copy:
    src: "{{ EXTRACT_DIR }}/node/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
    - kubelet
    - proxy

- name: Add kubernetes node systemd service unit
  template:
    src: "{{ item.src }}"
    dest: "/lib/systemd/system/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/kubelet.service.j2, dest: kubelet.service }
    - { src: setup/kube-proxy.service.j2, dest: proxy.service }

- name: Copy kubelet config file
  template:
    src: "{{ item.src }}"
    dest: "/var/lib/kubelet/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/kubelet-config.yaml.j2, dest: config.yaml }
    - { src: setup/kubelet.env.j2, dest: kubelet.env }

- name: Copy proxy config file
  template:
    src: "{{ item.src }}"
    dest: "/var/lib/kube-proxy/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/kube-proxy-config.yaml.j2, dest: config.yaml }
    - { src: setup/kube-proxy-kubeconfig.conf.j2, dest: kubeconfig.conf }
  notify: Enable and restart kubelet and proxy service

- include_tasks: setup-cni-plugin.yaml

- name: Copy kubernetes CA certificate
  synchronize:
    src: "{{ KUBERNETES_PKI_DIR }}/{{ KUBERNETES_CA_CERT_NAME }}" # k8s-server
    dest: "{{ KUBERNETES_PKI_DIR }}/{{ KUBERNETES_CA_CERT_NAME }}" # current host
  delegate_to: k8s-server