---
- name: Config apt source mirror
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0644

- name: Disable Auto Update
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '1'
    replace: '0'
    backup: yes

- name: Set Timezone
  timezone:
    name: Asia/Shanghai

# Register DNS record
- name: Register DNS record
  lineinfile:
    dest: /etc/bind/db.lan
    line: "{{ inventory_hostname }}.lan. IN A {{ public_ip_address }}"
    state: present
  delegate_to: bind

- name: Get bind public ip address
  set_fact:
    bind_public_ip: "{{ ansible_enp0s8.ipv4.address }}"
  delegate_to: bind

- name: Configure DNS
  replace:
    path: /etc/systemd/resolved.conf
    regexp: '#DNS='
    replace: "DNS={{ bind_public_ip }}"
    backup: yes

- name: Configure fallback DNS
  replace:
    path: /etc/systemd/resolved.conf
    regexp: '#FallbackDNS='
    replace: "FallbackDNS={{ fallback_dns }}"
    backup: yes

- name: Restart systemd-resolved service
  systemd:
    name: systemd-resolved
    state: restarted
