---
# APT
- name: Config apt source mirror
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0644

- name: Disable Auto Update
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '1'
    replace: '0'
    backup: yes
