---
# Certificate
- name: Slurp vault CA cert
  slurp:
    src: "{{ VAULT_CERT_DIR }}/{{ VAULT_CERT_NAME }}"
  register: vault_ca_crt
  delegate_to: vault

# todo 注意FQDN对应
- name: Copy CA cert
  copy:
    content: "{{ vault_ca_crt['content'] | b64decode }}"
    dest: "/usr/local/share/ca-certificates/{{ VAULT_FQDN }}.crt"

- name: Update CA certificate
  shell:
    cmd: update-ca-certificates
