---
- name: Required certificate
  set_fact:
    certificates:
      - "{{ VAULT_CERT_NAME }}"
      - "{{ ROOT_CERT_NAME }}"
      - "{{ INT_CERT_NAME }}"

- name: Slurp certificate
  slurp:
    src: "{{ VAULT_PKI_DIR }}/{{ item }}"
  register: cert_res
  delegate_to: vault
  with_items: "{{ certificates }}"

- name: Copy certificate
  copy:
    content: "{{ item.0.content | b64decode }}"
    dest: "/usr/local/share/ca-certificates/{{ item.1 }}"
  with_together:
    - "{{ cert_res.results }}"
    - "{{ certificates }}"

- name: Update certificate
  shell:
    cmd: update-ca-certificates