---
- name: Config hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars['vault'].ansible_host }} {{ VAULT_FQDN }} {{ VAULT_FQDN }}"
    state: present

- name: Slurp vault token
  include_tasks: ./slurp-vault-token.yaml

- name: Get vault seal status
  uri:
    method: GET
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/seal-status"
  register: seal_status

- name: Unseal vault
  uri:
    method: PUT
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/unseal"
    body_format: json
    body:
      key: "{{ item }}"
  with_items: "{{ vault_initialize_result['keys'] }}"
  when: not seal_status.json is search("cluster_id")
