---
- name: Add etcd peer role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int_ipool/roles/peer.etcd.ipool.me"
    body_format: json
    status_code: 204
    body:
      allow_any_name: true
      allowed_domains: peer.etcd.ipool.me

- name: Generate etcd peer certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int_ipool/issue/peer.etcd.ipool.me"
    body_format: json
    status_code: 200
    body:
      common_name: peer.etcd.ipool.me
      ip_sans: "{{ ansible_host }},127.0.0.1"
  register: certificate

- name: Persistent etcd peer certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: /opt/etcd/tls/peer.crt
    mode: 0644

- name: Persistent etcd peer key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: /opt/etcd/tls/peer.key
    mode: 0644
