- name: Install kubectl and kubelet
  apt:
    update_cache: yes
    name:
      - kubectl
      - kubelet

- name: Copy manifests file
  template:
    src: "{{ item.src }}"
    dest: "{{ kubernetes_manifests_directory }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/kube-apiserver.yaml.j2, dest: kube-apiserver.yaml }
    - { src: setup/kube-controller-manager.yaml.j2, dest: kube-controller-manager.yaml }
    - { src: setup/kube-scheduler.yaml.j2, dest: kube-scheduler.yaml }

- name: Add kubeconf config file
  template:
    src: "{{ item.src }}"
    dest: "{{ kubernetes_config_directory }}/{{ item.dest }}"
    mode: 0644
  notify: Restart kubernetes server service
  with_items:
    - { src: setup/controller-manager.conf.j2, dest: controller-manager.conf }
    - { src: setup/scheduler.conf.j2, dest: scheduler.conf }
    - { src: setup/admin.conf.j2, dest: admin.conf }