- name: Create kubernetes extract directory
  file:
    path: "{{ KUBERNETES_EXTRACT_DIR }}"
    state: directory

- name: Extract kubernetes package
  unarchive:
    src: "{{ KUBERNETES_SERVER_PACKAGE_NAME }}"
    dest: "{{ KUBERNETES_EXTRACT_DIR }}"
    creates: "{{ KUBERNETES_EXTRACT_DIR }}/server"
    extra_opts: [ "--strip-components=1" ]

- name: Install kubernetes components
  copy:
    remote_src: yes
    src: "{{ KUBERNETES_EXTRACT_DIR }}/server/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl
  notify: Restart kubernetes server service

- name: Add kubernetes basic systemd service
  copy:
    src: "{{ item.src }}"
    dest: "/lib/systemd/system/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/kube-apiserver.service, dest: kube-apiserver.service }
    - { src: setup/kube-controller-manager.service, dest: kube-controller-manager }
    - { src: setup/kube-scheduler.service, dest: kube-scheduler.service }
  notify: Restart kubernetes server service

- name: Add kubernetes custom server service
  template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/kube-{{ item.dest }}.service.d/10-{{ item.dest }}.conf"
    mode: 0644
  with_items:
    - { src: setup/apiserver.service.j2, dest: apiserver }
    - { src: setup/controller-manager.service.j2, dest: controller-manager }
    - { src: setup/scheduler.service.j2, dest: scheduler }
  notify: Restart kubernetes server service

- name: Slurp vault_int_ca.crt
  slurp:
    src: "{{ VAULT_PKI_DIR }}/{{ INT_CERT_NAME }}"
  register: int_cert
  delegate_to: vault

- include_tasks: template-controller-manager-conf.yaml
- include_tasks: template-admain-conf.yaml
- include_tasks: template-scheduler-conf.yaml
- include_tasks: copy-int-cert.yaml

- name: Copy kubectl config
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0644

- name: Add kubectl complete for bash
  lineinfile:
    dest: /root/.bashrc
    line: source /usr/share/bash-completion/bash_completion && source <(kubectl completion bash)
    state: present
