= Infrastructures

Based Ansible and Vagrant.

== Boot Order

PowerDNS
Vault
Etcd
Kubernetes Control plane
Kubernetes Worker

== notes

.test Etcd cluster
[source, bash]
----
cd /etc/etcd/pki/
etcdctl --cacert=ca.crt --cert=client.crt --key=client.key put hello world
----

.coredns deployment
[source, bash]
----
git clone https://github.com/coredns/deployment.git
# 10.96.0.10 在 playbooks/roles/kubernetes/node/setup/templates/kubelet-config.yaml.j2
./deploy.sh -s -i 10.96.0.10 > coredns-deployment.yaml
kubectl replace --force -f coredns-deployment.yaml 
----

.nginx ingress
[source, bash]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.45.0/deploy/static/provider/cloud/deploy.yaml
kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
----

Vault 和 Bind9 属于基础设施类服务，尽可能减少修改与配置，keep clean

== To Do

* [x] kubernetes 集群搭建
* [ ] 还有太多细节值得完善
* [ ] clean file
* [ ] github releast 下载可以借助https://ghproxy.com等实现
* [ ] 差个高配服务器,,,,啊
* [ ] 命名与可维护性
* [x] token 是直接生成到服务端和还是先存到本地，需要看有没有其他任务用到
* [x] 都在服务器上好，本地尽可能啥都不存
* [ ] 想上OpenStack然后配合Terraform、Packer、Ansible做到全面IAC。
* [ ] 未来目录等规范向minikube靠拢
* [ ] 创建目录的操作应该和变量声明一样，可能用到前才创建会好一些吧
* [ ] 多个Node使用同一token，会有冲突
* [ ] 一个ROLE只做一件事
* [ ] 每个软件最好都有自己的用户组和用户
* [ ] defaults vs vars
* [ ] allow_any_name
* [ ] 主动注册的形式更加灵活
* [ ] 注册的形式确实灵活，但权限逻辑上不太通
* [ ] 本机咱就别slurp了好不。嗯，好。
* [ ] 关闭swap
* [*] Kubeadm 它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!它不香吗!
* [*] DNS那货怎么搞奥
