# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.33.50"
  config.vm.hostname = "gitlab-server"

  config.vm.synced_folder "../../.cache/var/cache/apt", "/var/cache/apt"
  config.vm.synced_folder "../../.cache/var/lib/apt", "/var/lib/apt"
  config.vm.synced_folder "../../.cache/etc/apt", "/etc/apt"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../../playbooks/gitlab.yml"
  end
end
