# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "gitlab-server" do |gitlab|
    gitlab.vm.box = "ubuntu/focal64"
    gitlab.vm.box_check_update = false

    gitlab.vm.network "private_network", ip: "192.168.33.50"
    gitlab.vm.hostname = "gitlab-server"

    gitlab.vm.synced_folder "../../.cache/var/cache/apt", "/var/cache/apt"
    gitlab.vm.synced_folder "../../.cache/var/lib/apt", "/var/lib/apt"
    gitlab.vm.synced_folder "../../.cache/etc/apt", "/etc/apt"

    gitlab.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    gitlab.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
