---
- name: Add kube-proxy apiserver client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/roles/client.apiserver.kube-proxy.kubernetes.ipool.me"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      enforce_hostnames: false
      common_name: system:kube-proxy
      allow_any_name: true

- name: Generate kube-proxy apiserver client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/issue/client.apiserver.kube-proxy.kubernetes.ipool.me"
    body_format: json
    status_code: 200
    body:
      common_name: system:kube-proxy
  register: certificate

- name: Persistent kube-proxy apiserver client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: /opt/kubernetes/tls/kube-proxy-apiserver-client.crt
    mode: 0644

- name: Persistent kube-proxy apiserver client key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: /opt/kubernetes/tls/kube-proxy-apiserver-client.key
    mode: 0644

