# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "coredns" do |coredns|
    coredns.vm.box = "ubuntu/focal64"
    coredns.vm.box_check_update = false
    coredns.vm.network "private_network", ip: "192.168.33.10"
    coredns.vm.hostname = "coredns"

    coredns.vm.synced_folder "../.cache/var/cache/apt", "/var/cache/apt"
    coredns.vm.synced_folder "../.cache/var/lib/apt", "/var/lib/apt"
    coredns.vm.synced_folder "../.cache/etc/apt", "/etc/apt"

    coredns.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
    end

    coredns.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
