# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_ip = "192.168.33.10"
  config.vm.define "coredns" do |coredns|
    coredns.vm.box = "ubuntu/focal64"
    coredns.vm.box_check_update = false
    coredns.vm.network "private_network", ip: host_ip
    coredns.vm.hostname = "coredns"

    coredns.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    coredns.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.host_vars = {
        coredns.vm.hostname => {"ansible_host" => host_ip, "ansible_port" => 22}
      }
    end
  end
end
