---
- name: Install docker-ce and docker-compose
  apt:
    update_cache: yes
    name:
      - docker-compose
      - socat

- name: Create docker cert directory
  file:
    path: "/etc/docker/certs.d/{{ HARBOR_FQDN }}"
    state: directory
    mode: 0644

#- name: Slurp intermediate certificate
#  slurp:
#    src: "{{ VAULT_PKI_DIR }}/{{ INT_CERT_NAME }}"
#  register: int_cert
#  delegate_to: vault
#
#- name: Copy intermediate certificate
#  copy:
#    content: "{{ int_cert['content'] | b64decode }}"
#    dest: "{{ K8S_NODE_PKI_DIR }}/{{ INT_CERT_NAME }}"

# todo harbor certificate
#- name: Copy certificate and private key
#  copy:
#    src: "./roles/harbor/prepare/files/{{ item.src }}"
#    dest: "/etc/docker/certs.d/{{ HARBOR_FQDN }}/{{ item.dest }}"
#    mode: 0644
#  with_items:
#    - { src: "{{ HARBOR_FQDN }}.crt" , dest: "{{ HARBOR_FQDN }}.crt" }
#    - { src: "{{ HARBOR_FQDN }}.key" , dest: "{{ HARBOR_FQDN }}.key" }
#  notify: Restart docker service

- name: Copy daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker

- name: Restart docker service
  systemd:
    name: docker
    enabled: yes
    state: started
    daemon_reload: true
