---
- name: Create kubernetes config directory
  file:
    path: /root/.kube
    state: directory

- name: Copy kubectl config
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config

- name: Add kubectl complete for bash
  lineinfile:
    dest: /root/.bashrc
    line: source /usr/share/bash-completion/bash_completion && source <(kubectl completion bash)
    state: present

- name: Create kubernetes config yaml directory
  file:
    path: "/root/config"
    state: directory
    mode: 0755

- name: Copy cluster role binding.yaml for tls bootstraping
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - config/auto-approve-csrs-for-group.yaml
    - config/auto-approve-renewals-for-nodes.yaml
    - config/create-csrs-for-bootstrapping.yaml
    - config/kube-flannel.yaml

- name: Initializing cluster role binding
  shell:
    cmd: "kubectl apply -f {{ item }}"
    chdir: "/root/"
  with_items:
    - config/auto-approve-csrs-for-group.yaml
    - config/auto-approve-renewals-for-nodes.yaml
    - config/create-csrs-for-bootstrapping.yaml
    - config/kube-flannel.yaml
