---
- name: Restart kubernetes server service
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - kube-controller-manager
    - kube-scheduler
    - kube-apiserver
