---
- name: Create etcd pki directory
  file:
    path: "{{ SERVER_ETCD_PKI_DIR }}"
    state: directory
    mode: 0755

- name: Slurp etcd CA cert
  slurp:
    src: "{{ ETCD_PKI_DIR }}/{{ ETCD_CA_CERT_NAME }}"
  register: etcd_crt
  delegate_to: etcd1

- name: Persistent etcd CA cert
  copy:
    content: "{{ etcd_crt['content'] | b64decode }}"
    dest: "{{ SERVER_ETCD_PKI_DIR }}/{{ SERVER_ETCD_CA_CERT_NAME }}"
    mode: 0644
