---
- name: Add controller-manager apiserver client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/kubernetes/roles/system-kube-controller-manager"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      enforce_hostnames: false
      common_name: system:kube-controller-manager
      allow_any_name: true

- name: Generate controller-manager apiserver client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/kubernetes/issue/system-kube-controller-manager"
    body_format: json
    status_code: 200
    body:
      common_name: system:kube-controller-manager
  register: certificate

- name: Persistent controller-manager apiserver client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: "{{ KUBERNETES_PKI_DIR }}/{{ CONTROLLER_MANAGER_APISERVER_CLIENT_CERT_NAME }}"
    mode: 0644

- name: Persistent controller-manager apiserver client key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: "{{ KUBERNETES_PKI_DIR }}/{{ CONTROLLER_MANAGER_APISERVER_CLIENT_KEY_NAME }}"
    mode: 0644
