---
- name: Add apiserver kubelet client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/kubernetes/roles/kube-apiserver-kubelet-client"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      organization: system:masters
      common_name: kube-apiserver-kubelet-client
      allow_any_name: true

- name: Generate kube-apiserver kubelet client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/kubernetes/issue/kube-apiserver-kubelet-client"
    body_format: json
    status_code: 200
    body:
      common_name: kube-apiserver-kubelet-client
  register: certificate

- name: Persistent kube-apiserver kubelet client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: "{{ SERVER_PKI_DIR }}/{{ APISERVER_KUBELET_CLIENT_CERT_NAME }}"
    mode: 0644

- name: Persistent kube-apiserver kubelet client key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: "{{ SERVER_PKI_DIR }}/{{ APISERVER_KUBELET_CLIENT_KEY_NAME }}"
    mode: 0644
