---
# download
- name: Stat kubernetes server package
  become: no
  local_action:
    module: stat
    path: "{{ KUBERNETES_SERVER_PACKAGE_NAME }}"
  register: kubernetes_server_package_stat
- name: Try donwload kubernetes serverr package
  include_tasks: download.yaml
  when: not kubernetes_server_package_stat.stat.exists

- include_tasks: create-directory.yaml
- include_tasks: apiserver.yaml
- include_tasks: apiserver-etcd-client.yaml
- include_tasks: apiserver-kubelet-client.yaml
- include_tasks: controller-manager-apiserver-client.yaml
- include_tasks: scheduler-apiserver-client.yaml
- include_tasks: front-proxy-ca.yaml
- include_tasks: front-proxy-client.yaml
- include_tasks: sa.yaml
- include_tasks: admin.yaml
