---
# download
- name: Stat kubernetes server package
  become: no
  local_action:
    module: stat
    path: "{{ KUBERNETES_SERVER_PACKAGE_NAME }}"
  register: kubernetes_server_package_stat

- name: Try donwload kubernetes serverr package
  include_tasks: download-k8s-server-package.yaml
  when: not kubernetes_server_package_stat.stat.exists

# todo split it
- include_tasks: create-directory.yaml

# Generate certificate
- name: Waits vault service started
  wait_for:
    host: "{{ VAULT_FQDN }}"
    port: "{{ VAULT_PORT }}"

- name: Slurp vault token
  include_tasks: ../../../common/tasks/slurp-vault-token.yaml

- name: Create kubernetes PKI directory
  file:
    path: "{{ K8S_SERVER_PKI_DIR }}"
    state: directory
    mode: 0644

- include_tasks: mount-kubernetes-pki-secret-engine.yaml
- include_tasks: generate-kubernetes-ca.yaml
- include_tasks: gen-kube-apiserver-cert.yaml
- include_tasks: gen-kube-apiserver-etcd-client-cert.yaml
- include_tasks: gen-kube-apiserver-kubelet-client-cert.yaml
- include_tasks: gen-kube-controller-manager-kube-apiserver-client-cert.yaml
- include_tasks: gen-kube-scheduler-kube-apiserver-client-cert.yaml
- include_tasks: gen-service-account-cert.yaml
- include_tasks: gen-admin-cert.yaml
