---
# Enable intermediate PKI secret engine
- name: Mount PKI intermediate secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/kubernetes"
    body_format: json
    status_code: 204
    body:
      type: pki

- name: Tune PKI intermediate secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/kubernetes/tune"
    body_format: json
    status_code: 204
    body:
      description: Intermediate certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ PKI_TTL }}"