---
- name: Copy cluster role binding.yaml for tls bootstraping
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - auto-approve-csrs-for-group.yaml
    - auto-approve-renewals-for-nodes.yaml
    - create-csrs-for-bootstrapping.yaml
    - kube-flannel.yaml

- name: Initializing cluster role binding
  shell:
    cmd: "kubectl apply -f {{ item }}"
    chdir: "/root/"
  with_items:
    - auto-approve-csrs-for-group.yaml
    - auto-approve-renewals-for-nodes.yaml
    - create-csrs-for-bootstrapping.yaml
    - kube-flannel.yaml
