# Download
# kubernetes server
KUBERNETES_SERVER_DOWNLOAD_URL: "https://dl.k8s.io/{{ kubernetes_version }}/kubernetes-server-linux-amd64.tar.gz"
KUBERNETES_SERVER_PACKAGE_NAME: "{{ RESOURCES_PATH }}/kubernetes/kubernetes-server-{{ kubernetes_version }}-linux-amd64.tar.gz"
# flannel manifests
FLANNEL_MANIFESTS_DOWNLOAD_URL: https://ghproxy.com/https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
FLANNEL_MANIFESTS_FILE: "{{ RESOURCES_PATH }}/kubernetes/kube-flannel.yml"


# Certificate
# certificate directory
kubernetes_etcd_pki_directory: "{{ kubernetes_pki_directory }}/etcd"
# certificate authority

etcd_ca_certificate: etcd-ca.crt
SERVER_ETCD_CA_KEY_NAME: etcd-ca.key
front_proxy_ca_certificate: front-proxy-ca.crt
front_proxy_ca_key: front-proxy-ca.key
# certificate
ADMIN_CERT_NAME: admin.crt
ADMIN_KEY_NAME: admin.key
apiserver_etcd_client_certificate: apiserver-etcd-client.crt
apiserver_etcd_client_key: apiserver-etcd-client.key
apiserver_certificate: apiserver.crt
apiserver_key: apiserver.key
apiserver_kubelet_client_certificate: apiserver-kubelet-client.crt
apiserver_kubelet_client_key: apiserver-kubelet-client.key
controller_manager_apiserver_client_certificate: controller-manager-apiserver-client.crt
controller_manager_apiserver_client_key: controller-manager-apiserver-client.key
FRONT_PROXY_CLIENT_CERT_NAME: front-proxy-client.crt
FRONT_PROXY_CLIENT_KEY_NAME: front-proxy-client.key
schedule_apiserver_client_certificate: schedule-apiserver-client.crt
schedule_apiserver_client_key: schedule-apiserver-client.key
service_account_certificate: service-account.crt
service_account_key: service-account.key
