# Download
# kubernetes server
KUBERNETES_SERVER_DOWNLOAD_URL: "https://dl.k8s.io/{{ KUBERNETES_VERSION }}/kubernetes-server-linux-amd64.tar.gz"
KUBERNETES_SERVER_PACKAGE_NAME: "{{ RESOURCES_PATH }}/kubernetes/kubernetes-server-{{ KUBERNETES_VERSION }}-linux-amd64.tar.gz"
# flannel manifests
FLANNEL_MANIFESTS_DOWNLOAD_URL: https://ghproxy.com/https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
FLANNEL_MANIFESTS_FILE: "{{ RESOURCES_PATH }}/kubernetes/kube-flannel.yml"


# Certificate
# certificate directory
SERVER_ETCD_PKI_DIR: "{{ SERVER_PKI_DIR }}/etcd"
# certificate authority
SERVER_CA_KEY_NAME: ca.key
SERVER_ETCD_CA_CERT_NAME: etcd-ca.crt
SERVER_ETCD_CA_KEY_NAME: etcd-ca.key
FRONT_PROXY_CA_CERT_NAME: front-proxy-ca.crt
FRONT_PROXY_CA_KEY_NAME: front-proxy-ca.key
# certificate
ADMIN_CERT_NAME: admin.crt
ADMIN_KEY_NAME: admin.key
APISERVER_ETCD_CLIENT_CERT_NAME: apiserver-etcd-client.crt
APISERVER_ETCD_CLIENT_KEY_NAME: apiserver-etcd-client.key
APISERVER_CERT_NAME: apiserver.crt
APISERVER_KEY_NAME: apiserver.key
APISERVER_KUBELET_CLIENT_CERT_NAME: apiserver-kubelet-client.crt
APISERVER_KUBELET_CLIENT_KEY_NAME: apiserver-kubelet-client.key
CONTROLLER_MANAGER_APISERVER_CLIENT_CERT_NAME: controller-manager-apiserver-client.crt
CONTROLLER_MANAGER_APISERVER_CLIENT_KEY_NAME: controller-manager-apiserver-client.key
FRONT_PROXY_CLIENT_CERT_NAME: front-proxy-client.crt
FRONT_PROXY_CLIENT_KEY_NAME: front-proxy-client.key
SCHEDULE_APISERVER_CLIENT_CERT_NAME: schedule-apiserver-client.crt
SCHEDULE_APISERVER_CLIENT_KEY_NAME: schedule-apiserver-client.key
SERVICE_ACCOUNT_CERT_NAME: service-account.crt
SERVICE_ACCOUNT_KEY_NAME: service-account.key
