---
- name: Create harbor directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ HARBOR_PKI_DIR }}"
    - /opt/harbor/data

- name: Extract harbor offline package
  unarchive:
    src: "{{ HARBOR_PACK }}"
    dest: /opt/harbor
    extra_opts: [ "--strip-components=1" ]
    creates: /opt/harbor/install.sh

- name: Copy generate harbor.yaml script
  copy:
    src: generate-harbor.yaml.py
    dest: /opt/harbor/generate-harbor.yaml.py
    mode: 0755

- name: Copy harbor certificate
  copy:
    src: "./roles/harbor/prepare/files/{{ item }}"
    dest: "/opt/harbor/tls/{{ item }}"
    mode: 0644
  with_items:
    - "{{ HARBOR_FQDN }}.crt"
    - "{{ HARBOR_FQDN }}.key"

- name: Generate harbor.yaml
  shell: ./generate-harbor.yaml.py
  args:
    chdir: /opt/harbor
  notify: Restart harbor
