# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_ip =  "192.168.33.40"

  config.vm.define "harbor" do |harbor|
    harbor.vm.box = "ubuntu/xenial64"
    harbor.vm.box_check_update = false
    harbor.vm.hostname = "harbor"
    harbor.vm.network "private_network", ip: host_ip

    harbor.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    harbor.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.host_vars = {
        harbor.vm.hostname => {"ansible_host" => host_ip, "ansible_port" => 22}
      }
    end
  end
end
