# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "harbor" do |harbor|
    harbor.vm.box = "ubuntu/focal64"
    harbor.vm.hostname = "harbor"
    harbor.vm.network "public_network"
    harbor.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    harbor.vm.provision :ansible do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yaml"
    end
  end
end
