# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "harbor" do |harbor|
    harbor.vm.box = "ubuntu/focal64"
    harbor.vm.box_check_update = false

    harbor.vm.hostname = "harbor"
    harbor.vm.network "private_network", ip: "192.168.33.40"

    harbor.vm.synced_folder "../.cache/var/cache/apt", "/var/cache/apt"
    harbor.vm.synced_folder "../.cache/var/lib/apt", "/var/lib/apt"
    harbor.vm.synced_folder "../.cache/etc/apt", "/etc/apt"

    harbor.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    harbor.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
