---
# Generate intermediate CA
- name: Generate intermediate CA csr
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/intermediate/generate/internal"
    body_format: json
    status_code: 200
    body:
      common_name: ipool.me
  register: intermediate_ca_csr

- name: Sign intermediate CA
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/root/sign-intermediate"
    body_format: json
    body:
      csr: "{{ intermediate_ca_csr.json.data.csr }}"
  register: int_ca_crt

- name: Persistent intermediate CA certificate result
  copy:
    content: "{{ int_ca_crt.json.data.certificate }}"
    dest: "{{ VAULT_CERT_DIR }}/{{ INT_CERT_NAME }}"

- name: Set sign intermediate certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/intermediate/set-signed"
    body_format: json
    status_code: 204
    body:
      certificate: "{{ int_ca_crt.json.data.certificate }}"
