---
- name: Config vault service
  template:
    src: "vault.hcl.j2"
    dest: "/etc/vault.d/vault.hcl"
    mode: 0644
    group: vault
    owner: vault

- name: Enable and start vault service
  systemd:
    name: vault
    enabled: yes
    state: started

- name: Config hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_host }} {{ VAULT_FQDN }} {{ VAULT_FQDN }}"
    state: present

# Initialize vault
- name: Check vault initialize stat
  stat:
    path: "{{ VAULT_PKI_DIR }}/{{ VAULT_INITIALIZE_RESULT }}"
  register: vault_init

- name: Try initialize vault
  include_tasks: initialize-vault.yaml
  when: not vault_init.stat.exists

- name: Unseal vault
  include_tasks: ../../../common/prepare/tasks/unseal-vault.yaml

- name: Try mount pki root cecret engine
  include_tasks: mount-root-pki-secret-engine.yaml

- name: Try generate root CA certificate
  include_tasks: generate-root-ca.yaml

- name: Try mount pki int cecret engine
  include_tasks: mount-int-pki-secret-engine.yaml

- name: Try generate int CA certificate
  include_tasks: generate-int-ca.yaml
