---
# Enable PKI secret engine
- name: Mount PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/pki/root"
    body_format: json
    status_code: 204
    body:
      type: pki

- name: Tune PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/pki/root/tune"
    body_format: json
    status_code: 204
    body:
      description: Root certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ MAX_PKI_TTL }}"
