---
- name: Waits vault service started
  wait_for:
    host: "{{ VAULT_DOMAIN }}"
    port: "{{ VAULT_PORT }}"

- name: Slurp vault initialize result
  slurp:
    src: "{{ VAULT_PKI_DIR }}/{{ VAULT_INITIALIZE_RESULT }}"
  register: vault_initialize_result

- name: Base64 decode vault initialize result
  set_fact:
    vault_initialize_result: "{{ vault_initialize_result['content'] | b64decode }}"

- name: Unseal vault
  uri:
    method: PUT
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/sys/unseal"
    body_format: json
    body:
      key: "{{ item }}"
  with_items: "{{ vault_initialize_result['keys'] }}"
