# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_ip = "192.168.33.70"

  config.vm.define "kubernetes_node" do |kubernetes|
    kubernetes.vm.box = "ubuntu/focal64"
    kubernetes.vm.box_check_update = false
    kubernetes.vm.network "private_network", ip: host_ip
    kubernetes.vm.hostname = "kubernetes-node"

    kubernetes.vm.synced_folder "../../.cache/var/cache/apt", "/var/cache/apt"
    kubernetes.vm.synced_folder "../../.cache/var/lib/apt", "/var/lib/apt"
    kubernetes.vm.synced_folder "../../.cache/etc/apt", "/etc/apt"

    kubernetes.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    kubernetes.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.host_vars = {
        kubernetes.vm.hostname => {"ansible_host" => host_ip, "ansible_port" => 22}
      }
    end
  end
end
