---
- name: Initialize the Kubernetes cluster using kubeadm
  command: "kubeadm init --apiserver-advertise-address {{ PUBLIC_IP }} --image-repository {{ IMAGE_REPOSITORY }} --pod-network-cidr=192.168.0.0/16"

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install calico pod network
  become: no
  command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Download nginx ingress yaml
  get_url:
    url: "{{ nginx_ingress_url }}"
    dest: /tmp/nginx-ingress.yaml

- name: Replace nginx ingress yaml
  replace:
    path: /tmp/nginx-ingress.yaml
    regexp: '^(.*)k8s.gcr.io/ingress-nginx/controller:v(0.46.0).*'
    replace: "\\1{{ IMAGE_REPOSITORY }}/nginx-ingress-controller:v\\2"