# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "ubuntu/focal64"
    gitlab.vm.network "public_network", bridge: "enp2s0"
    gitlab.vm.hostname = "gitlab"
    gitlab.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    gitlab.vm.provision :ansible do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yaml"
    end
  end
end
