# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_ip = "192.168.33.50"
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "ubuntu/focal64"
    gitlab.vm.box_check_update = false

    gitlab.vm.network "private_network", ip: host_ip
    gitlab.vm.hostname = "gitlab"

    gitlab.vm.synced_folder "../../.cache/var/cache/apt", "/var/cache/apt"
    gitlab.vm.synced_folder "../../.cache/var/lib/apt", "/var/lib/apt"
    gitlab.vm.synced_folder "../../.cache/etc/apt", "/etc/apt"

    gitlab.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end

    gitlab.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.host_vars = {
        gitlab.vm.hostname => {"ansible_host" => host_ip, "ansible_port" => 22}
      }
    end
  end
end
