---
# Mount PKI secret engine
- name: Mount PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/pki"
    body_format: json
    status_code: 204
    body:
      type: pki

- name: Tune PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/pki/tune"
    body_format: json
    status_code: 204
    body:
      description: Root certificate
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ MAX_PKI_TTL }}"

# Submit CA certificate
- name: Slurp vault key
  slurp:
    src: "{{ VAULT_KEY_DIR }}/tls.key"
  register: vault_key

- name: Base64 decode vault_key
  set_fact:
    vault_key: "{{ vault_key['content'] | b64decode}}"

- name: Slurp vault crt
  slurp:
    src: "{{ VAULT_KEY_DIR }}/tls.crt"
  register: vault_crt

- name: Base64 decode vault_crt
  set_fact:
    vault_crt: "{{ vault_crt['content'] | b64decode}}"

- name: Submit CA certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_init_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/config/ca"
    body_format: json
    status_code: 204
    body:
      pem_bundle: "{{ vault_key + '\n' +  vault_crt }}"