---
- name: Enable and start vault service
  systemd:
    name: vault
    enabled: yes
    state: restarted

- name: Check vault init stat
  stat:
    path: "{{ VAULT_KEY_DIR }}/init-result.json"
  register: vault_init

- name: Try init vault
  include_tasks: init.yaml
  when: not vault_init.stat.exists
