# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  vms = []

  (1..2).each do |i|
    config.vm.define "kubernetes-worker#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.network "public_network"
      node.vm.hostname = "kubernetes-worker#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
      end

      vms << node.vm.hostname
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yaml"
    ansible.groups = { "kubernetes_worker" => vms }
  end
end
