---
- name: Online install vault
  include_tasks:
    file: online-install.yaml
  when: not VAULT_OFFLINE_INSTALL

- name: Offline install vault
  include_tasks:
    file: offline-install.yaml
  when: VAULT_OFFLINE_INSTALL

- name: Set default vault server
  lineinfile:
    dest: /root/.bashrc
    line: export VAULT_ADDR=https://vault.ipool.me:8200
    state: present

- name: Check vault CA key stat
  stat:
    path: "{{ VAULT_KEY_DIR }}/tls.csr"
  register: vault_ca_key_stat

- include_tasks:
    file: generate-ca-key.yaml
  when: not vault_ca_key_stat.stat.exists
