---
- name: Create vault group
  group:
    name: vault

- name: Create vault with group vault
  user:
    name: vault
    group: vault

- name: Create vault packages directory
  file:
    path: "{{ VAULT_CERT_DIR }}"
    state: directory
    group: vault
    owner: vault
    mode: 0755

- name: Generate an CA private key
  openssl_privatekey:
    path: "{{ VAULT_CERT_DIR }}/{{ VAULT_KEY_NAME }}"
    group: vault
    owner: vault
    mode: 0600

- name: Generate an CA certificate signing request
  openssl_csr:
    path: "{{ VAULT_CERT_DIR }}/{{ VAULT_CSR_NAME }}"
    privatekey_path: "{{ VAULT_CERT_DIR }}/{{ VAULT_KEY_NAME }}"
    common_name: "{{ VAULT_FQDN }}"
    basic_constraints: 'CA:TRUE'
    email_address: "admin@eastack.me"
    country_name: "CN"
    state_or_province_name: "ShanDong"
    locality_name: "JiNan"
    group: vault
    owner: vault
    mode: 0600

- name: Generate a self signed CA certificate
  openssl_certificate:
    privatekey_path: "{{ VAULT_CERT_DIR }}/{{ VAULT_KEY_NAME }}"
    csr_path: "{{ VAULT_CERT_DIR }}/{{ VAULT_CSR_NAME }}"
    path: "{{ VAULT_CERT_DIR }}/{{ VAULT_CERT_NAME }}"
    provider: selfsigned
    group: vault
    owner: vault
    mode: 0600
