---
# download
- name: Stat vault package
  become: no
  local_action:
    module: stat
    path: "{{ VAULT_PACKAGE_NAME }}"
  register: vault_package_stat

- name: Try download vault package
  include_tasks: download-vault.yaml
  when: not vault_package_stat.stat.exists

- name: Generate certificate
  include_tasks: generate-certificate.yaml

- name: Create group and user
  include_tasks: create-user.yaml