---
# download
- name: Stat vault package
  become: no
  local_action:
    module: stat
    path: "{{ VAULT_PACKAGE_NAME }}"
  register: vault_package_stat

- name: Try download vault package
  include_tasks: download-vault.yaml
  when: not vault_package_stat.stat.exists

- name: Create group and user
  include_tasks: create-user.yaml

- name: Generate certificate
  include_tasks: generate-certificate.yaml

- name: Setup certificate
  include_tasks: setup-certificate.yaml

- name: Config hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_host }} {{ VAULT_FQDN }} {{ VAULT_FQDN }}"
    state: present