# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_ip = "192.168.33.60"

  config.vm.define "k8s-server" do |kubernetes|
    kubernetes.vm.box = "ubuntu/xenial64"
    kubernetes.vm.box_check_update = false
    kubernetes.vm.network "private_network", ip: host_ip
    kubernetes.vm.hostname = "k8s-server"
    kubernetes.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    kubernetes.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.host_vars = {
        kubernetes.vm.hostname => {"ansible_host" => host_ip, "ansible_port" => 22}
      }
    end
  end
end
