# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "kubernetes-server" do |kubernetes|
    kubernetes.vm.box = "ubuntu/focal64"
    kubernetes.vm.box_check_update = false

    kubernetes.vm.network "private_network", ip: "192.168.33.60"
    kubernetes.vm.hostname = "kubernetes-server"

    kubernetes.vm.synced_folder "../../.cache/var/cache/apt", "/var/cache/apt"
    kubernetes.vm.synced_folder "../../.cache/var/lib/apt", "/var/lib/apt"
    kubernetes.vm.synced_folder "../../.cache/etc/apt", "/etc/apt"

    kubernetes.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    kubernetes.vm.provision :ansible do |ansible|
      ansible.playbook = "../../../playbooks/kubernetes-server.yml"
    end
  end
end
