---
# Generate front proxy CA
- name: Generate front proxy CA csr
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/front-proxy/intermediate/generate/exported"
    body_format: json
    status_code: 200
    body:
      common_name: front-proxy-ca
  register: front_proxy_ca_csr

- name: Sign front proxy CA
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/root/root/sign-intermediate"
    body_format: json
    body:
      csr: "{{ front_proxy_ca_csr.json.data.csr }}"
  register: front_proxy_ca_crt

- name: Set sign front proxy certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki/front-proxy/intermediate/set-signed"
    body_format: json
    status_code: 204
    body:
      certificate: "{{ front_proxy_ca_crt.json.data.certificate }}"

- name: Persistent front proxy CA certificate
  copy:
    content: "{{ front_proxy_ca_crt.json.data.certificate }}"
    dest: "{{ kubernetes_pki_directory }}/{{ front_proxy_ca_certificate }}"

- name: Persistent front proxy CA key
  copy:
    content: "{{ front_proxy_ca_csr.json.data.private_key }}"
    dest: "{{ kubernetes_pki_directory }}/{{ front_proxy_ca_key }}"
