---
- name: Mount front proxy PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/pki/front-proxy"
    body_format: json
    status_code: 204
    body:
      type: pki

- name: Tune front proxy PKI secret engine
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/sys/mounts/pki/front-proxy/tune"
    body_format: json
    status_code: 204
    body:
      description: Front proxy certificate authority
      max_lease_ttl: "{{ MAX_PKI_TTL }}"
      default_lease_ttl: "{{ PKI_TTL }}"