---
- name: Add admin role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/roles/admin.kubernetes.ipool.me"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      organization: system:masters
      common_name: kubernetes-admin
      allow_any_name: true

- name: Generate admin certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/issue/admin.kubernetes.ipool.me"
    body_format: json
    status_code: 200
    body:
      common_name: kubernetes-admin
  register: admin_certificate

- name: Persistent admin certificate
  copy:
    content: "{{ admin_certificate.json.data.certificate }}"
    dest: /opt/kubernetes/tls/admin.crt
    mode: 0644

- name: Persistent admin key
  copy:
    content: "{{ admin_certificate.json.data.private_key }}"
    dest: /opt/kubernetes/tls/admin.key
    mode: 0644
