---
- name: Add apiserver etcd client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/roles/client.etcd.apiserver.kubernetes.ipool.me"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      organization: system:masters
      common_name: kube-apiserver-etcd-client
      allow_any_name: true

- name: Generate apiserver etcd client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/issue/client.etcd.apiserver.kubernetes.ipool.me"
    body_format: json
    status_code: 200
    body:
      common_name: kube-apiserver-etcd-client
      organization: system:masters
  register: client_certificate

- name: Persistent apiserver etcd client certificate
  copy:
    content: "{{ client_certificate.json.data.certificate }}"
    dest: /opt/kubernetes/tls/apiserver-etcd-client.crt
    mode: 0644

- name: Persistent apiserver etcd client key
  copy:
    content: "{{ client_certificate.json.data.private_key }}"
    dest: /opt/kubernetes/tls/apiserver-etcd-client.key
    mode: 0644
