---
- name: Add scheduler apiserver client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int_ipool/roles/client.apiserver.scheduler.kubernetes.ipool.me"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      enforce_hostnames: false
      common_name: system:kube-scheduler
      allow_any_name: true

- name: Generate scheduler apiserver client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int_ipool/issue/client.apiserver.scheduler.kubernetes.ipool.me"
    body_format: json
    status_code: 200
    body:
      common_name: system:kube-scheduler
  register: certificate

- name: Persistent scheduler apiserver client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: /opt/kubernetes/tls/scheduler-apiserver-client.crt
    mode: 0644

- name: Persistent scheduler apiserver client certificate
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: /opt/kubernetes/tls/scheduler-apiserver-client.key
    mode: 0644
