---
- name: Load kernel module br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Config kernel parameter
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
