---
- name: Slurp kubernetes certificate
  slurp:
    src: "{{ kubernetes_pki_directory }}/{{ kubernetes_ca_certificate }}"
  register: kubernetes_ca
  delegate_to: k8s-server

- name: Persistent kubernetes certificate
  copy:
    content: "{{ kubernetes_ca['content'] | b64decode }}"
    dest: "{{ kubernetes_pki_directory }}/{{ kubernetes_ca_certificate }}"
