---
- name: Add kube-proxy kube-apiserver client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/kubernetes/roles/system-kube-proxy"
    body_format: json
    status_code: 204
    body:
      key_usage: ["DigitalSignature", "KeyEncipherment"]
      ext_key_usage: ["ClientAuth"]
      enforce_hostnames: false
      common_name: system:kube-proxy
      allow_any_name: true

- name: Generate kube-proxy kube-apiserver client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/kubernetes/issue/system-kube-proxy"
    body_format: json
    status_code: 200
    body:
      common_name: system:kube-proxy
  register: certificate

- name: Persistent kube-proxy kube-apiserver client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: "{{ K8S_NODE_PKI_DIR }}/{{ KUBE_PROXY_KUBE_APISERVER_CLIENT_CERT_NAME }}"
    mode: 0644

- name: Persistent kube-proxy kube-apiserver client key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: "{{ K8S_NODE_PKI_DIR }}/{{ KUBE_PROXY_KUBE_APISERVER_CLIENT_KEY_NAME }}"
    mode: 0644

