---
# download
- name: Stat kubernetes node package
  become: no
  local_action:
    module: stat
    path: "{{ NODE_PACKAGE_NAME }}"
  register: node_package_stat

- name: Try donwload kubernetes node package
  include_tasks: download-node-package.yaml
  when: not node_package_stat.stat.exists

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/kubernetes/package
    - /opt/cni/package
    - /opt/cni/bin
    - /opt/kubernetes/tls
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /etc/kubernetes/manifests
    - /etc/kubernetes/pki
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/kube-proxy.service.d

- include_tasks: gen-kube-proxy-cert.yaml
- include_tasks: copy-kubernetes-ca.yaml
- include_tasks: config-bootstrap-config.yaml
- include_tasks: pull-docker-image.yaml
