---
# download
- name: Stat kubernetes node package
  become: no
  local_action:
    module: stat
    path: "{{ KUBERNETES_NODE_PACKAGE_NAME }}"
  register: kubernetes_node_package_stat

- name: Try donwload kubernetes node package
  include_tasks: download-k8s-node-package.yaml
  when: not kubernetes_node_package_stat.stat.exists

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/kubernetes/package
    - /opt/cni/package
    - /opt/cni/bin
    - /opt/kubernetes/tls
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /etc/kubernetes/manifests
    - /etc/kubernetes/pki
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/kube-proxy.service.d

- name: Slurp intermediate certificate
  slurp:
    src: "{{ SERVER_PKI_DIR }}/{{ SERVER_CA_CERT_NAME }}"
  register: int_cert
  delegate_to: k8s-server

- include_tasks: config-kernel.yaml
- include_tasks: gen-kube-proxy-cert.yaml
- include_tasks: config-bootstrap-token.yaml
- include_tasks: pull-docker-image.yaml
