---
- name: Stat vault package
  become: no
  local_action:
    module: stat
    path: "{{ VAULT_PACKAGE }}"
  register: vault_package

- name: Create vault packages directory
  become: no
  local_action:
    module: file
    path: "{{ RESOURCES_PATH }}/vault"
    state: directory
    mode: 0755

- name: Download vault binary package
  become: no
  local_action:
    module: get_url
    url: "{{ VAULT_DOWNLOAD_URL }}"
    dest:  "{{ VAULT_PACKAGE }}"
  when: not vault_package.stat.exists
