---
- name: Add gitlab role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/roles/{{ GITLAB_FQDN }}"
    body_format: json
    status_code: 204
    body:
      allowed_domains: "{{ GITLAB_FQDN }}"
      allow_any_name: true
      allow_subdomains: yes

- name: Generate gitlab certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_FQDN }}:{{ VAULT_PORT }}/v1/pki_int/issue/{{ GITLAB_FQDN }}"
    body_format: json
    status_code: 200
    body:
      common_name: "{{ GITLAB_FQDN }}"
      ip_sans: "{{ ansible_host }}"
  register: certificate

- name: Persistent gitlab certificate
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.certificate }}"
    dest: "./roles/gitlab/server/prepare/{{ GITLAB_FQDN }}.crt"
    mode: 0644

- name: Persistent gitlab key
  become: no
  local_action:
    module: copy
    content: "{{ certificate.json.data.private_key }}"
    dest: "./roles/gitlab/server/prepare/{{ GITLAB_FQDN }}.key"
    mode: 0644
