Vagrant.configure("2") do |config|
  config.vm.define :vault do |vault|
    vault.vm.box = "debian/buster64"
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = "vault"
    libvirt.uri = 'qemu:///system'
  end

  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
