- name: Install kubectl
  apt:
    update_cache: yes
    name: kubectl

- name: Config autocomplete
  lineinfile:
    path: /root/.bashrc
    line: source <(kubectl completion bash)
    state: present

- name: Copy manifests file
  template:
    src: "{{ item.src }}"
    dest: "{{ kubernetes_manifests_directory }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/kube-apiserver.yaml.j2, dest: kube-apiserver.yaml }
    - { src: setup/kube-controller-manager.yaml.j2, dest: kube-controller-manager.yaml }
    - { src: setup/kube-scheduler.yaml.j2, dest: kube-scheduler.yaml }

- name: Add kubeconf config file
  template:
    src: "{{ item.src }}"
    dest: "{{ kubernetes_config_directory }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: setup/controller-manager.conf.j2, dest: controller-manager.conf }
    - { src: setup/scheduler.conf.j2, dest: scheduler.conf }
    - { src: setup/admin.conf.j2, dest: admin.conf }

- name: Copy conofig kubelet service
  copy:
    content: "{{ root_certificate.json.data.certificate }}"
    dest: "{{ VAULT_PKI_DIR }}/{{ ROOT_CERT_NAME }}"

- name: Copy kubelet conofig file
  template:
    src: setup/kubelet.conf.j2
    dest: /var/lib/kubelet/config.yaml
