---
- name: Create etcd directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/etcd
    - /var/lib/etcd

- name: Extract etcd package
  unarchive:
    src: "{{ ETCD_PACKAGE }}"
    dest: /opt/etcd
    extra_opts: [ '--strip-components=1' ]
    creates: /opt/etcd/etcdctl

- name: Copy etcdctl to /usr/bin
  copy:
    src: "/opt/etcd/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
    - etcd
    - etcdctl
  notify: Enable and restart etcd service

- name: Add etcd systemd service
  copy:
    src: etcd.service
    dest: /usr/lib/systemd/system/etcd.service
    mode: 0644
  notify: Enable and restart etcd service

- name: Generate etcd environment file
  template:
    src: etcd.j2
    dest: /etc/etcd/etcd
    mode: 0644
  notify: Enable and restart etcd service

- name: Slurp vault int crt
  slurp:
    src: "{{ VAULT_CERT_DIR }}/vault_int_ca.crt"
  register: vault_int_crt
  delegate_to: vault

- name: Base64 decode vault_int_crt
  set_fact:
    vault_int_crt: "{{ vault_int_crt['content'] | b64decode}}"

- name: Copy CA certificate
  copy:
    content: "{{ vault_int_crt }}"
    dest: /opt/etcd/tls/ca.crt
    mode: 0644
  notify: Enable and restart etcd service
