# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "bind" do |bind|
    bind.vm.box = "ubuntu/focal64"
    bind.vm.hostname = "bind"
    bind.vm.network "private_network", type: "dhcp"
    bind.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    bind.vm.provision :ansible do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yaml"
    end
  end
end
