# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_ip = "192.168.33.10"

  config.vm.define "bind" do |bind|
    bind.vm.box = "ubuntu/focal64"
    bind.vm.box_check_update = false
    bind.vm.network "private_network", ip: host_ip
    bind.vm.hostname = "bind"
    bind.vm.synced_folder "../../.vagrant/", "/var/cache/apt/", owner: "root", group: "root"
    bind.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    bind.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.host_vars = {
        bind.vm.hostname => {"ansible_host" => host_ip, "ansible_port" => 22}
      }
    end
  end
end
