Vagrant.configure("2") do |config|
  config.vm.define :vault do |vault|
    vault.vm.box = "debian/buster64"
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = "vault"
    libvirt.uri = 'qemu:///system'
  end

#  $script = <<-SCRIPT
#    export DEBIAN_FRONTEND=noninteractive
#    sudo apt-get update
#    sudo apt-get install -y gpg
#  SCRIPT
#  config.vm.provision "shell", inline: $script
#
#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "../ansible/playbook.yml"
#  end

  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
