---
- name: Create etcd directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ ETCD_WORKING_DIR }}"
    - "{{ ETCD_EXTRACT_DIR }}"

- name: Extract etcd package
  unarchive:
    src: "{{ ETCD_PACKAGE_NAME }}"
    dest: "{{ ETCD_EXTRACT_DIR }}"
    extra_opts: [ '--strip-components=1' ]
    creates: "{{ ETCD_EXTRACT_DIR }}/etcdctl"

- name: Copy etcdctl to /usr/bin
  copy:
    src: "{{ ETCD_EXTRACT_DIR }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: yes
    mode: 0755
  with_items:
    - etcd
    - etcdctl
  notify: Enable and restart etcd service

- name: Add basic etcd systemd service
  template:
    src: etcd.service
    dest: /usr/lib/systemd/system/etcd.service
    mode: 0644