# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..1).each do |i|
    config.vm.define "etcd#{i}" do |etcd|
      etcd.vm.box = "ubuntu/focal64"
      etcd.vm.box_check_update = false

      etcd.vm.network "private_network", ip: "192.168.33.3#{i}"
      etcd.vm.hostname = "etcd#{i}"

      etcd.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end

      etcd.vm.provision :ansible do |ansible|
        ansible.playbook = "../../playbooks/etcd.yml"
      end
    end
  end
end
