# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  vms = []

  (1..3).each do |i|
    config.vm.define "etcd#{i}" do |etcd|
      etcd.vm.box = "ubuntu/focal64"
      etcd.vm.network "private_network", type: "dhcp"
      etcd.vm.hostname = "etcd#{i}"
      etcd.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end

      vms << node.vm.hostname

      etcd.vm.provision :ansible do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yaml"
        ansible.groups = { "etcd" => vms }
      end
    end
  end
end
