# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  host_vars = {}

  (1..1).each do |i|
    config.vm.define "etcd#{i}" do |etcd|
      host_ip = "192.168.33.3#{i}"
      host_vars.store("etcd#{i}", {"ansible_host" => host_ip, "ansible_port" => 22})

      etcd.vm.box = "ubuntu/focal64"
      etcd.vm.box_check_update = false
      etcd.vm.network "private_network", ip: host_ip
      etcd.vm.hostname = "etcd#{i}"
      etcd.vm.provider "virtualbox" do |vb|
        vb.memory = "640"
      end

      etcd.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.groups = { "etcd" => host_vars.keys }
        ansible.host_vars = host_vars
      end
    end
  end
end
