---
- name: Initialize
  become: yes
  hosts: all
  tasks:
  - name: Disable APT auto update
    replace:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: '1'
      replace: '0'
      backup: yes

  - name: Set Timezone
    timezone:
      name: Asia/Shanghai
