---
- name: Initialize
  become: yes
  hosts: all

  tasks:
  - name: Patch vagrant ansible inventory
    replace:
      path: "/vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
      regexp: "127.0.0.1"
      replace: "{{ ansible_enp0s8.ipv4.address }}"
