---
- name: Create Etcd packages directory
  become: no
  local_action:
    module: file
    path: "{{ RESOURCES_PATH }}/etcd"
    state: directory
    mode: 0755

- name: Download Etcd node binary package
  become: no
  local_action:
    module: get_url
    url: "{{ ETCD_DOWNLOAD_URL }}"
    dest:  "{{ ETCD_PACKAGE_NAME }}"