---
- name: Add Etcd client role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/pki_int/roles/client.{{ ETCD_DOMAIN }}"
    body_format: json
    status_code: 204
    body:
      allow_any_name: true
      enforce_hostnames: false
      allowed_domains: "{{ ETCD_DOMAIN }},localhost"

- name: Generate etcd client certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/pki_int/issue/client.{{ ETCD_DOMAIN }}"
    body_format: json
    status_code: 200
    body:
      common_name: "{{ ETCD_DOMAIN }},localhost"
      ip_sans: "{{ PUBLIC_IP_ADDRESS }},127.0.0.1"
  register: certificate

- name: Persistent etcd client certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: "{{ ETCD_PKI_DIR }}/{{ ETCD_CLIENT_CERT_NAME }}"
    mode: 0644

- name: Persistent etcd client key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: "{{ ETCD_PKI_DIR }}/{{ ETCD_CLIENT_KEY_NAME }}"
    mode: 0644
