---
# Download Etcd package
- name: Stat Etcd package
  become: no
  local_action:
    module: stat
    path: "{{ ETCD_PACKAGE_NAME }}"
  register: etcd_package_stat

- name: Try donwload Etcd package
  include_tasks: download-etcd.yaml
  when: not etcd_package_stat.stat.exists

# Generate certificate
- name: Create Etcd certificate directory
  file:
    path: "{{ ETCD_PKI_DIR }}"
    state: directory
    mode: 0755

- include_tasks: gen-peer-cert.yaml
- include_tasks: gen-client-cert.yaml
