# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "vault" do |vault|
    vault.vm.box_check_update = false
    vault.vm.box = "ubuntu/focal64"
    vault.vm.network "public_network"
    vault.vm.hostname = "vault"
    vault.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    vault.vm.provision :ansible do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yaml"
    end
  end
end
