# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "vault" do |vault|
    vault.vm.box = "ubuntu/focal64"
    vault.vm.box_check_update = false

    vault.vm.network "private_network", ip: "192.168.33.20"
    vault.vm.hostname = "vault"

    vault.vm.synced_folder "../.cache/var/cache/apt", "/var/cache/apt"
    vault.vm.synced_folder "../.cache/var/lib/apt", "/var/lib/apt"
    vault.vm.synced_folder "../.cache/etc/apt", "/etc/apt"

    vault.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end

    vault.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
