---
- name: Add Harbor role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/pki_int/roles/{{ HARBOR_DOMAIN }}"
    body_format: json
    status_code: 204
    body:
      allow_any_name: true
      allowed_domains: "{{ HARBOR_DOMAIN }}"

- name: Generate Harbor certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/pki_int/issue/{{ HARBOR_DOMAIN }}"
    body_format: json
    status_code: 200
    body:
      common_name: "{{ HARBOR_DOMAIN }}"
      ip_sans: "{{ PUBLIC_IP }}"
  register: certificate

- name: Persistent Harbor certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: "{{ HARBOR_PKI_DIR }}/{{ HARBOR_DOMAIN }}.crt"
    mode: 0644

- name: Persistent Harbor key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: "{{ HARBOR_PKI_DIR }}/{{ HARBOR_DOMAIN }}.key"
    mode: 0644
