---
- include_tasks: download.yaml

- name: Check harbor private key stat
  become: no
  local_action:
    module: stat
    path: "./roles/harbor/prepare/files/{{ HARBOR_DOMAIN }}.key"
  register: certificate_file

- include_tasks: gen-harbor-cert.yaml
  when: not certificate_file.stat.exists
