- name: Setup PowerDNS and Dependence
  apt:
    update_cache: yes
    name:
      - pdns-server
      - pdns-tools
      - pdns-backend-sqlite3
      - sqlite3
      - python3-dnspython

- name: Copy SQL Schema
  copy:
    src: schema.sqlite3.sql
    dest: /var/lib/powerdns/schema.sqlite3.sql
    owner: pdns
    mode: 0755

- name: Create SQLite tables for PowerDNS
  command:
    cmd: "sqlite3 -init schema.sqlite3.sql pdns.sqlite3 .quit"
    chdir: /var/lib/powerdns

- name: Change file ownership, group and permissions
  file:
    path: /var/lib/powerdns/pdns.sqlite3
    owner: pdns
    group: pdns

- name: Generate PowerDNS configuration
  template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    mode: 0600

- name: Restart PowerDNS
  systemd:
    name: pdns
    state: restarted

- name: "Create zone for {{ ZONE }}"
  command: "pdnsutil create-zone {{ ZONE }}"

- name: Update DNS Server address
  become: no
  local_action:
    module: replace
    path: "group_vars/all.yaml"
    regexp: 'DNS: (.*$)'
    replace: "DNS: {{ PUBLIC_IP }}"
