- name: Setup PowerDNS and Dependence
  apt:
    update_cache: yes
    name:
      - pdns-server
      - pdns-tools
      - pdns-backend-sqlite3
      - sqlite3
      - python3-dnspython

- name: Copy SQL Schema
  copy:
    src: schema.sqlite3.sql
    dest: /var/lib/powerdns/schema.sqlite3.sql
    owner: pdns
    mode: 0755

- name: Create SQLite tables for PowerDNS
  command:
    cmd: "sqlite3 -init schema.sqlite3.sql pdns.sqlite3 .quit"
    chdir: /var/lib/powerdns

- name: Config PowerDNS
  blockinfile:
    path: /etc/powerdns/pdns.conf
    block: |
      dnsupdate=yes
      allow-dnsupdate-from=127.0.0.0/8,::1,{{ PUBLIC_IP_ADDRESS }}
      launch=gsqlite3
      gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
      local-address={{ PUBLIC_IP_ADDRESS }}