---
- name: Add GitLab role
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/pki_int/roles/{{ GITLAB_DOMAIN }}"
    body_format: json
    status_code: 204
    body:
      allow_any_name: true
      allowed_domains: "{{ GITLAB_DOMAIN }}"

- name: Generate GitLab certificate
  uri:
    method: POST
    headers:
      X-Vault-Token: "{{ vault_initialize_result['root_token'] }}"
    url: "https://{{ VAULT_DOMAIN }}:{{ VAULT_PORT }}/v1/pki_int/issue/{{ GITLAB_DOMAIN }}"
    body_format: json
    status_code: 200
    body:
      common_name: "{{ GITLAB_DOMAIN }}"
      ip_sans: "{{ PUBLIC_IP }}"
  register: certificate

- name: Create certificate directory
  file:
    path: /etc/gitlab/ssl
    state: directory
    mode: 0644

- name: Persistent GitLab certificate
  copy:
    content: "{{ certificate.json.data.certificate }}"
    dest: "/etc/gitlab/ssl/{{ GITLAB_DOMAIN }}.crt"
    mode: 0644

- name: Persistent GitLab key
  copy:
    content: "{{ certificate.json.data.private_key }}"
    dest: "/etc/gitlab/ssl/{{ GITLAB_DOMAIN }}.key"
    mode: 0644
