---
- name: Config docker daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Restart docker service
  systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Add kubernetes mirror key
  apt_key:
    url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg.asc
    state: present

- name: Add kubernetes mirror
  apt_repository:
    repo: deb http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install kubelet and kubeadm
  apt:
    update_cache: yes
    name:
      - kubelet
      - kubeadm
      - socat
      - conntrack
      - apt-transport-https
      - gnupg-agent
      - software-properties-common

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Load kernel module br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Config kernel parameter
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ ansible_enp0s8.ipv4.address }}"
    create: yes

- name: Enable kubelet
  service:
    name: kubelet
    daemon_reload: yes
    enabled: yes

- name: Pull coredns docker image
  docker_image:
    name: "coredns/coredns:{{ coredns_version }}"
    repository: "{{ image_repository }}/coredns/coredns:v{{ coredns_version }}"
    source: pull
