---
- name: Create Etcd config directory
  file:
    path: "{{ ETCD_CONFIG_DIR }}"
    state: directory
    mode: 0755

- name: Generate Etcd environment file
  template:
    src: etcd.j2
    dest: "{{ ETCD_CONFIG_DIR }}/etcd.env"
    mode: 0644
  notify: Enable and restart Etcd service