# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  vms = []

  config.vm.define "kubernetes-control-plane" do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.network "public_network"
    node.vm.hostname = "kubernetes-control-plane"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    vms << node.vm.hostname
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yaml"
    ansible.groups = { "kubernetes_control_plane" => vms }
  end
end
